#!/usr/bin/env bash
set -e

# The commit-msg receives one parameter; the pathname to a temporary file
# containing the user's commit message.

# Get the path to the directory containing this script.
DIR="$( cd "$( dirname "${BASH_SOURCE[0]}" )" && pwd )"

# Configure "commit-msg.*" to resolve to an empty set if there are no matches,
# instead of the string "commit-msg.*".
shopt -s nullglob

# Execute all commit-msg.* handlers.
for hook_handler in $DIR/commit-msg.*; do
    # Some people have a `commit-msg.sample` file that is in `.git/hooks` by
    # default. Ignore that so that file so that we don't run the sample hook.
    if [ "`basename "$hook_handler"`" != "commit-msg.sample" ]
    then
        "$hook_handler" "$@"
    fi
done
